sudo: required
dist: trusty
language: cpp
compiler: gcc

env:
  global:
    - MAKEOPTS=-j3
  matrix:
    - PYVERSION=python2.6
    - PYVERSION=python2.7
    - PYVERSION=python3.4
    - PYVERSION=python3.5
    - PYVERSION=python3.6
    - PYVERSION=python3.7

addons:
  apt:
    sources:
      - sourceline: 'ppa:deadsnakes/ppa'
      - autotools-dev
      - libtool
      - pkg-config

install:
  - sudo sysctl kernel.yama.ptrace_scope=0
  - travis_retry sudo apt-get update
  - travis_retry sudo apt-get install --allow-unauthenticated "${PYVERSION}"{,-minimal,-dev}

# Travis puts some other Python versions in /opt, so it's very important that we
# use an explicit /usr/bin path when running the tests.
script:
  - ./autogen.sh
  - ./configure --disable-silent-rules --enable-werror
  - make $MAKEOPTS
  - file ./src/pyflame
  - ./runtests.sh -v /usr/bin/"${PYVERSION}"
